---
# Install & Configure Vagrant
- name: Add Hashicorp signing key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  become: yes
  when: ansible_pkg_mgr == 'apt'
  tags: [ vagrant ]

- name:  Add Hashicorp repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com groovy main
    state: present
    filename: hashicorp-vagrant
  become: yes
  when: ansible_pkg_mgr == 'apt'
  tags: [ vagrant ]

- name: Install Vagrant Package from Hashicorp
  apt:
    update_cache: True
    pkg:
    - vagrant
  become: yes
  when: ansible_pkg_mgr == 'apt'
  tags: [ vagrant ]
