---
# Install & Configure Chrome

- name: Add Google signing key
  ansible.builtin.apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name:  Add Google Chrome repository
  ansible.builtin.apt_repository:
    repo: deb http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome
  when: ansible_pkg_mgr == 'apt'
  tags: [ chrome ]

- name: Install Google Chrome Package
  apt:
    update_cache: True
    pkg:
    - google-chrome-stable
  become: yes
  when: ansible_pkg_mgr == 'apt'
  tags: [ chrome ]
