---

nodejs_version: node_15.x
nodejs_ppa: deb https://deb.nodesource.com/{{ nodejs_version }} groovy main
nodejs_ppa_key: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
nodejs_ppa_id: 1655A0AB68576280
